In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array([[9.0,8.0,7.0], [6,5,4]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
a.ndim
b.shape


7.0

In [20]:
b[0,:]
b[1 , 1]
# b[0,2]

5.0

In [22]:
b[1,2]=10
print(b)

[[ 9.  8.  7.]
 [ 6.  5. 10.]]


In [24]:
b[: , 2]=[20,30]
print(b)

[[ 9.  8. 20.]
 [ 6.  5. 30.]]


In [26]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
#get specific element (work outside in)
c[0,1,1]
c[:,1,:]

array([[3, 4],
       [7, 8]])

In [72]:
np.zeros((2,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [48]:
np.random.rand(4,2)

array([[0.07432681, 0.19354935],
       [0.91145789, 0.34359595],
       [0.70958554, 0.94311504],
       [0.66868017, 0.98456682]])

In [51]:
np.random.randint(-2,8, size=(3,3))

array([[-1,  2,  0],
       [ 1,  2,  2],
       [ 5,  2,  6]])

In [53]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [73]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4, 1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [81]:
stats=np.array([[1,6,3],[4,7,6]])
stats

array([[1, 6, 3],
       [4, 7, 6]])

In [82]:
np.max(stats, axis=1)

array([6, 7])

In [84]:
np.sum(stats, axis=0)


array([ 5, 13,  9])

In [88]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [95]:
for i in range(1,4):
    print(i)

1
2
3
